import * as stylex from '@stylexjs/stylex';

export const toolbarStyles = stylex.create({
  toolbar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 4,
    padding: '8px 12px',
    backgroundColor: 'var(--color-background-surface, #ffffff)',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    zIndex: 10,
  },
  group: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
  },
  divider: {
    width: 1,
    height: 20,
    backgroundColor: 'var(--color-border)',
    margin: '0 4px',
  },
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    borderRadius: 6,
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: 'var(--color-text-secondary)',
    cursor: 'pointer',
    outline: 'none',
    transition: 'all 0.15s ease',
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
      color: 'var(--color-text-primary)',
    },
    ':disabled': {
      opacity: 0.4,
      cursor: 'not-allowed',
    },
  },
  buttonActive: {
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
    fontWeight: 600,
  },
  select: {
    padding: '4px 8px',
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    backgroundColor: 'var(--color-background-surface, #ffffff)',
    color: 'var(--color-text-primary, #111827)',
    cursor: 'pointer',
    outline: 'none',
    height: 32,
  },
});
