import {
    AbandonQuizSessionUseCase,
    AddTermToSubjectUseCase,
    ArchiveQuestionUseCase,
    ArchiveQuizUseCase,
    ClearAnnotationsUseCase,
    CreateAndAssignTermUseCase,
    CreateMaterialUseCase,
    CreateQuestionUseCase,
    CreateQuizUseCase,
    CreateSubjectUseCase,
    CreateTermUseCase,
    DeleteMaterialUseCase,
    DeleteSubjectUseCase,
    DeleteTermUseCase,
    ImportMaterialUseCase,
    ImportSubjectUseCase,
    PublishQuestionUseCase,
    PublishQuizUseCase,
    RecordFlashcardReviewUseCase,
    RemoveImportedMaterialUseCase,
    RemoveTermFromSubjectUseCase,
    ReorderSubjectsUseCase,
    ReorderSubjectTermsUseCase,
    SaveDrawingUseCase,
    SaveHighlightUseCase,
    SaveQuizUseCase,
    StartQuizSessionUseCase,
    SubmitQuizSessionUseCase,
    SyncDefaultTermsUseCase,
    SyncSubjectTermsUseCase,
    TouchMaterialUseCase,
    UnarchiveQuestionUseCase,
    UnarchiveQuizUseCase,
    UpdateDocumentContentUseCase,
    UpdateMaterialUseCase,
    UpdateQuestionUseCase,
    UpdateQuizUseCase,
    UpdateSubjectUseCase,
    UpdateTermUseCase,
    GetGlobalAnalyticsUseCase,
    GetSubjectAnalyticsUseCase,
    GetMaterialAnalyticsUseCase,
} from '../../application';
import type { Repositories } from './createRepositories';

export function createUseCases(repositories: Repositories) {
    return {
        flashcards: {
            recordReview: new RecordFlashcardReviewUseCase(repositories.flashcardReviewRepository),
        },
        quiz: {
            startSession: new StartQuizSessionUseCase(repositories.quizSessionRepository),
            submitSession: new SubmitQuizSessionUseCase(repositories.quizSessionRepository),
            abandonSession: new AbandonQuizSessionUseCase(repositories.quizSessionRepository),
        },
        quizManagement: {
            createQuestion: new CreateQuestionUseCase(repositories.questionRepository),
            updateQuestion: new UpdateQuestionUseCase(repositories.questionRepository),
            archiveQuestion: new ArchiveQuestionUseCase(repositories.questionRepository),
            unarchiveQuestion: new UnarchiveQuestionUseCase(repositories.questionRepository),
            publishQuestion: new PublishQuestionUseCase(repositories.questionRepository),
            createQuiz: new CreateQuizUseCase(repositories.quizRepository),
            updateQuiz: new UpdateQuizUseCase(repositories.quizRepository),
            archiveQuiz: new ArchiveQuizUseCase(repositories.quizRepository),
            unarchiveQuiz: new UnarchiveQuizUseCase(repositories.quizRepository),
            publishQuiz: new PublishQuizUseCase(repositories.quizRepository),
            saveQuiz: new SaveQuizUseCase(repositories.questionRepository, repositories.quizEditorService),
        },
        library: {
            createMaterial: new CreateMaterialUseCase(repositories.libraryRepository, repositories.subjectTermRepository),
            updateMaterial: new UpdateMaterialUseCase(repositories.libraryRepository, repositories.subjectTermRepository),
            deleteMaterial: new DeleteMaterialUseCase(repositories.libraryRepository),
            touchMaterial: new TouchMaterialUseCase(repositories.libraryRepository),
            importMaterial: new ImportMaterialUseCase(repositories.catalogRepository, repositories.quizContentRepository, repositories.documentRepository, repositories.libraryImportService),
            importSubject: new ImportSubjectUseCase(repositories.catalogRepository, repositories.libraryRepository, repositories.quizContentRepository, repositories.documentRepository, repositories.libraryImportService),
            removeImportedMaterial: new RemoveImportedMaterialUseCase(repositories.libraryImportService),
            syncDefaultTerms: new SyncDefaultTermsUseCase(repositories.catalogRepository, repositories.termRepository),
        },
        subject: {
            createSubject: new CreateSubjectUseCase(repositories.subjectRepository),
            updateSubject: new UpdateSubjectUseCase(repositories.subjectRepository),
            reorderSubjects: new ReorderSubjectsUseCase(repositories.subjectRepository),
            deleteSubject: new DeleteSubjectUseCase(repositories.subjectRepository, repositories.libraryRepository),
            createTerm: new CreateTermUseCase(repositories.termRepository),
            updateTerm: new UpdateTermUseCase(repositories.termRepository),
            deleteTerm: new DeleteTermUseCase(repositories.termRepository),
            createAndAssignTerm: new CreateAndAssignTermUseCase(repositories.termService),
            syncTerms: new SyncSubjectTermsUseCase(repositories.subjectTermRepository, repositories.termRepository),
            reorderTerms: new ReorderSubjectTermsUseCase(repositories.subjectTermRepository),
            addTerm: new AddTermToSubjectUseCase(repositories.subjectTermRepository),
            removeTerm: new RemoveTermFromSubjectUseCase(repositories.subjectTermRepository),
        },
        reader: {
            saveHighlight: new SaveHighlightUseCase(repositories.annotationRepository),
            saveDrawing: new SaveDrawingUseCase(repositories.annotationRepository),
            clearAnnotations: new ClearAnnotationsUseCase(repositories.annotationRepository),
        },
        content: {
            updateDocumentContent: new UpdateDocumentContentUseCase(repositories.documentContentRepository),
        },
        analytics: {
            getGlobalAnalytics: new GetGlobalAnalyticsUseCase(repositories.analyticsRepository),
            getSubjectAnalytics: new GetSubjectAnalyticsUseCase(repositories.analyticsRepository),
            getMaterialAnalytics: new GetMaterialAnalyticsUseCase(repositories.analyticsRepository),
        },
    };
}

export type UseCases = ReturnType<typeof createUseCases>;
