import * as stylex from '@stylexjs/stylex';

/** StyleX rules for `CollectionHero` and its extracted subcomponents. */
export const styles = stylex.create({
  hero: {
    width: '100%',
    boxSizing: 'border-box',
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
  },
  topRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  topRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  hubBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: '0.13em',
    textTransform: 'uppercase',
    color: 'var(--color-text-secondary)',
  },
  hubDot: {
    width: 6,
    height: 6,
    borderRadius: 9999,
  },
  iconButton: {
    position: 'relative',
    width: 54,
    height: 54,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    cursor: 'pointer',
    padding: 0,
    // Visible (not hidden) so the focus badge can straddle the
    // bottom-right border; the hover overlay clips itself via its own
    // border radius below.
    overflow: 'visible',
    transition: 'transform 0.16s ease, box-shadow 0.16s ease, border-color 0.16s ease',
    ':hover': {
      transform: 'scale(1.06)',
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.12)',
    },
    ':active': {
      transform: 'scale(0.98)',
    },
    ':focus-visible': {
      outline: '2px solid var(--color-accent)',
      outlineOffset: 3,
    },
  },
  iconBlurOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 13,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
    backdropFilter: 'blur(3px)',
    color: 'var(--color-on-dark)',
    opacity: 0,
    pointerEvents: 'none',
    transition: 'opacity 0.18s ease',
  },
  iconBlurOverlayVisible: {
    opacity: 1,
  },
  iconEditBadge: {
    position: 'absolute',
    // Straddles the bottom-right border (half in, half out) so the
    // badge sits on the frame edge without covering the logo glyph.
    right: -7,
    bottom: -7,
    width: 20,
    height: 20,
    borderRadius: 9999,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'var(--color-background-surface)',
    color: 'var(--color-text-secondary)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    boxShadow: '0 1px 4px rgba(0, 0, 0, 0.18)',
    opacity: 0,
    transform: 'scale(0.6)',
    pointerEvents: 'none',
    transition: 'opacity 0.18s ease, transform 0.18s ease',
  },
  iconEditBadgeVisible: {
    opacity: 1,
    transform: 'scale(1)',
  },
  content: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  titleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    maxWidth: 680,
  },
  titleEditIcon: {
    color: 'var(--color-text-secondary)',
    flexShrink: 0,
    opacity: 0.6,
  },
  titleInput: {
    width: '100%',
    boxSizing: 'border-box',
    fontSize: 32,
    lineHeight: 1.25,
    minHeight: 48,
    fontWeight: 600,
    letterSpacing: '-0.5px',
    color: 'var(--color-text-primary)',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderRadius: 8,
    padding: '6px 10px',
    marginLeft: -10,
    outline: 'none',
    transition: 'border-color 0.16s ease',
    ':hover': {
      borderColor: 'var(--color-border, rgba(120, 115, 140, 0.25))',
    },
    ':focus': {
      borderColor: 'var(--color-accent)',
      backgroundColor: 'transparent',
    },
  },
  descriptionInput: {
    width: '100%',
    boxSizing: 'border-box',
    fontSize: 13.5,
    lineHeight: 1.5,
    minHeight: 44,
    color: 'var(--color-text-secondary)',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderRadius: 8,
    padding: '10px 12px',
    marginLeft: -8,
    outline: 'none',
    transition: 'border-color 0.16s ease',
    ':hover': {
      borderColor: 'var(--color-border, rgba(120, 115, 140, 0.25))',
    },
    ':focus': {
      borderColor: 'var(--color-accent)',
      backgroundColor: 'transparent',
    },
  },
  stats: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    flexWrap: 'wrap',
    fontSize: 12,
    color: 'var(--color-text-secondary)',
    marginTop: 14,
    marginBottom: 4,
  },
  statItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
  },
  statIcon: {
    color: 'var(--color-text-secondary)',
    flexShrink: 0,
  },
  statValue: {
    fontWeight: 600,
    color: 'var(--color-text-primary)',
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 12,
  },
  helper: {
    fontSize: 12,
    color: 'var(--color-text-secondary)',
    marginTop: 8,
  },
});
