import type { LibraryRepository, CreateMaterialInput } from '../../../domain/library/repositories/LibraryRepository';
import type { StudyMaterial } from '../../../domain/library/models/StudyMaterial';
import type { DocumentContentRepository, ImportedDocumentContent } from '../../../domain/reader/repositories/DocumentContentRepository';
import type { ImportAssetRepository, ImportedAsset } from '../../../domain/importer/repositories/ImportAssetRepository';
import type { ImportMetadata } from '../../../domain/importer/models/importer.types';

export interface CommitImportInput {
  /** User-reviewed title */
  title: string;
  /** User-reviewed Markdown content */
  markdown: string;
  /** Original file for asset preservation */
  file: File;
  /** Import provenance metadata */
  importMetadata: ImportMetadata;
  /** Optional subject assignment */
  subjectId?: string;
  /** Optional term assignment */
  termId?: string;
}

export class CommitImportUseCase {
  private readonly libraryRepository: LibraryRepository;
  private readonly documentContentRepository: DocumentContentRepository;
  private readonly importAssetRepository: ImportAssetRepository;

  constructor(
    libraryRepository: LibraryRepository,
    documentContentRepository: DocumentContentRepository,
    importAssetRepository: ImportAssetRepository,
  ) {
    this.libraryRepository = libraryRepository;
    this.documentContentRepository = documentContentRepository;
    this.importAssetRepository = importAssetRepository;
  }

  async execute(input: CommitImportInput): Promise<StudyMaterial> {
    const id = crypto.randomUUID();
    const documentId = `imported-${id}`;
    const now = new Date().toISOString();

    // Create StudyMaterial in library
    const materialInput: CreateMaterialInput = {
      title: input.title,
      documentId,
      subjectId: input.subjectId,
      termId: input.termId,
    };
    
    // In the prompt this was casted directly but CreateMaterialInput doesn't have id/createdAt, 
    // instead createMaterial creates it and returns the material.
    // However, if the repository expects an id to be generated by the use case:
    // Some implementations might expect it. We will cast it if we need to pass the ID, 
    // but standard CreateMaterialInput omits it. We'll pass it as any if we need the ID to match.
    // Wait, let's just pass `materialInput` and see if `material.id` works.
    
    const material = await this.libraryRepository.createMaterial(materialInput);
    const actualMaterialId = material.id;
    const actualDocumentId = material.documentId;

    const documentContent: ImportedDocumentContent = {
      documentId: actualDocumentId,
      title: input.title,
      content: input.markdown,
      updatedAt: now,
    };

    const asset: ImportedAsset = {
      materialId: actualMaterialId,
      blob: input.file,
      mimeType: input.file.type || 'application/octet-stream',
      filename: input.importMetadata.originalFilename,
      importedAt: now,
    };

    await this.documentContentRepository.put(documentContent);
    await this.importAssetRepository.put(asset);

    return material;
  }
}
