import * as stylex from '@stylexjs/stylex';

const tablet = '@media (min-width: 641px)';
const desktop = '@media (min-width: 1024px)';

export const styles = stylex.create({
  hero: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    padding: '22px 24px',
    marginBottom: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    background:
      'linear-gradient(115deg, var(--color-accent-muted), var(--color-background-surface) 60%)',
  },
  heroLead: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    minWidth: 240,
    flex: 1,
  },
  heroIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 52,
    height: 52,
    borderRadius: 16,
    flexShrink: 0,
    backgroundColor: 'var(--color-background-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    color: 'var(--color-accent)',
  },
  heroBody: {
    minWidth: 0,
  },
  heroEyebrow: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--color-text-secondary)',
    margin: 0,
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: 600,
    letterSpacing: '-0.01em',
    color: 'var(--color-text-primary)',
    margin: '6px 0 0',
  },
  heroMeta: {
    fontSize: 13,
    color: 'var(--color-text-secondary)',
    margin: '4px 0 0',
  },
  heroActions: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
  statStrip: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: 12,
    marginBottom: 32,
    [tablet]: {
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    },
  },
  statCard: {
    padding: '16px 18px',
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    backgroundColor: 'var(--color-background-surface)',
  },
  statLabelRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    fontSize: 13,
    color: 'var(--color-text-secondary)',
  },
  statValue: {
    fontSize: 28,
    fontWeight: 600,
    letterSpacing: '-0.02em',
    color: 'var(--color-text-primary)',
    margin: '14px 0 0',
  },
  statNote: {
    fontSize: 12,
    color: 'var(--color-text-disabled)',
    margin: '6px 0 0',
  },
  section: {
    marginBottom: 32,
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
    margin: 0,
  },
  recentGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: 12,
    [tablet]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    [desktop]: {
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    },
  },
  recentCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    padding: '14px 16px',
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    backgroundColor: 'var(--color-background-surface)',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'border-color 0.18s ease, background-color 0.18s ease',
    ':hover': {
      borderColor: 'var(--color-accent)',
      backgroundColor: 'var(--color-background-muted)',
    },
    ':focus-visible': {
      outline: '2px solid var(--color-accent)',
      outlineOffset: '2px',
    },
  },
  recentIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderRadius: 12,
    flexShrink: 0,
    backgroundColor: 'var(--color-background-muted)',
    color: 'var(--color-accent)',
  },
  recentBody: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  },
  recentTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
    margin: 0,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  recentMeta: {
    fontSize: 12,
    color: 'var(--color-text-secondary)',
    margin: 0,
  },
  quickActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
  },
});
