import * as stylex from '@stylexjs/stylex';

export const cardStyles = stylex.create({
  interactive: {
    cursor: 'pointer',
    position: 'relative',
    transition: 'transform 0.18s ease, box-shadow 0.18s ease',
    ':hover': {
      transform: 'translateY(-2px)',
    },
    ':focus-visible': {
      outline: '2px solid var(--color-accent)',
      outlineOffset: '2px',
    },
  },
  clickableArea: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    padding: 16,
    userSelect: 'none',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  titleColumn: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    minWidth: 0,
  },
  title: {
    fontSize: 16,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
    margin: 0,
    lineHeight: 1.3,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  /**
   * The card's single keyboard/AT affordance: opening the material. The card
   * container itself is presentational so the badge and action controls inside
   * it keep independent semantics and focus order.
   */
  titleButton: {
    display: 'block',
    width: '100%',
    padding: 0,
    margin: 0,
    borderWidth: 0,
    borderStyle: 'none',
    backgroundColor: 'transparent',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    fontWeight: 'inherit',
    lineHeight: 'inherit',
    color: 'inherit',
    textAlign: 'left',
    cursor: 'pointer',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    ':focus-visible': {
      outline: '2px solid var(--color-accent)',
      outlineOffset: '2px',
      borderRadius: 4,
    },
  },
  description: {
    fontSize: 13,
    color: 'var(--color-text-secondary)',
    margin: 0,
    lineHeight: 1.5,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  badgeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  tagsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    flexWrap: 'wrap',
  },
  tagChip: {
    textTransform: 'none',
    fontWeight: 600,
  },
  metaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 12,
    color: 'var(--color-text-disabled)',
  },
  actionBar: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 8,
    marginTop: 4,
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  popover: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: 8,
    backgroundColor: 'var(--color-background-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    boxShadow: '0 8px 24px rgba(0,0,0,0.3)',
    zIndex: 100,
    minWidth: 280,
    maxWidth: 360,
  },
  popoverHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
  },
  popoverHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  popoverTitle: {
    fontWeight: 600,
    fontSize: 14,
    color: 'var(--color-text-primary)',
  },
  popoverSubtitle: {
    fontSize: 12,
    color: 'var(--color-text-secondary)',
    margin: 0,
    marginTop: 4,
  },
  popoverList: {
    maxHeight: 300,
    overflowY: 'auto',
    padding: 8,
  },
  popoverEmpty: {
    fontSize: 13,
    color: 'var(--color-text-secondary)',
    padding: 16,
    textAlign: 'center',
  },
  /** Rendered as a real <button> so each collection toggle is independently focusable. */
  popoverRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    padding: '8px 12px',
    borderRadius: 8,
    borderWidth: 0,
    borderStyle: 'none',
    backgroundColor: 'transparent',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    textAlign: 'left',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
    },
    ':focus-visible': {
      outline: '2px solid var(--color-accent)',
      outlineOffset: '-2px',
    },
  },
  popoverIcon: {
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: 'solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  popoverRowLabel: {
    fontSize: 13,
    color: 'var(--color-text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: 1,
  },
  popoverCheck: {
    color: 'var(--color-success)',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
  },
  popoverPlus: {
    color: 'var(--color-text-secondary)',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
  },
  membershipSection: {
    marginTop: 4,
  },
  membershipEmpty: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontSize: 12,
    color: 'var(--color-text-disabled)',
  },
  badgeButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '2px 6px',
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    fontSize: 11,
    textDecoration: 'none',
    margin: 0,
  },
  badgeButtonClickable: {
    cursor: 'pointer',
  },
  badgeButtonStatic: {
    cursor: 'default',
  },
  badgeLabel: {
    maxWidth: 80,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
});
