import * as stylex from '@stylexjs/stylex';


const fadeIn = stylex.keyframes({
  from: { opacity: 0 },
  to: { opacity: 1 },
});

const slideUp = stylex.keyframes({
  from: { transform: 'translateY(100%)' },
  to: { transform: 'translateY(0)' },
});

export const styles = stylex.create({
  /**
   * Collections trigger button (icon-only). Mirrors the rail/dock icon-button
   * geometry so it slots into either container unchanged. Active highlight
   * (`navItemActive` equivalent) is applied by the host via StyleX props.
   */
  trigger: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 0,
    borderStyle: 'none',
    backgroundColor: 'transparent',
    color: 'var(--color-text-secondary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'background-color 0.18s ease, color 0.18s ease, border-color 0.18s ease',
    outline: 'none',
    flexShrink: 0,
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
      color: 'var(--color-text-primary)',
    },
  },
  triggerDock: {
    flex: '0 1 44px',
    minWidth: 32,
    flexShrink: 1,
  },
  triggerActive: {
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
    ':hover': {
      backgroundColor: 'var(--color-accent-muted)',
      color: 'var(--color-accent)',
    },
  },
  /**
   * Floating collections panel. Rendered through a portal at a position computed
   * from the trigger's bounding rect, so it escapes the rail/dock
   * `overflow: hidden` containers. Hidden at ≥1024px (desktop owns the sidebar).
   */
  panel: {
    position: 'fixed',
    zIndex: 180,
    width: 256,
    maxWidth: 'calc(100vw - 32px)',
    maxHeight: 'min(360px, 60vh)',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'var(--color-background-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 16,
    boxShadow: '0 16px 48px -8px rgba(0, 0, 0, 0.35)',
    boxSizing: 'border-box',
    overflow: 'hidden',
    '@media (max-width: 768px), (min-width: 1024px)': {
      display: 'none',
    },
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 14,
    paddingBottom: 12,
    paddingLeft: 16,
    paddingRight: 12,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    flexShrink: 0,
  },
  panelHeaderLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--color-text-secondary)',
  },
  panelBody: {
    overflowY: 'auto',
    overflowX: 'hidden',
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 6,
    paddingRight: 6,
    scrollbarWidth: 'thin',
    scrollbarColor: 'var(--color-border) transparent',
  },
  collectionRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 12,
    borderWidth: 0,
    borderStyle: 'none',
    backgroundColor: 'transparent',
    color: 'var(--color-text-secondary)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: 13.5,
    fontWeight: 500,
    textAlign: 'left',
    transition: 'background-color 0.15s ease, color 0.15s ease',
    boxSizing: 'border-box',
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
      color: 'var(--color-text-primary)',
    },
  },
  collectionRowActive: {
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
    fontWeight: 600,
    ':hover': {
      backgroundColor: 'var(--color-accent-muted)',
      color: 'var(--color-accent)',
    },
  },
  collectionIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: 0,
  },
  collectionLabel: {
    flex: 1,
    minWidth: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  countBadge: {
    flexShrink: 0,
    fontSize: 10,
    fontWeight: 600,
    lineHeight: 1.4,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 6,
    paddingRight: 6,
    borderRadius: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    color: 'var(--color-text-secondary)',
  },
  panelEmpty: {
    fontSize: 13,
    lineHeight: 1.5,
    color: 'var(--color-text-secondary)',
    paddingTop: 18,
    paddingBottom: 18,
    paddingLeft: 16,
    paddingRight: 16,
    textAlign: 'center',
  },
  newCollectionRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 16,
    paddingRight: 16,
    borderWidth: 0,
    borderStyle: 'none',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    backgroundColor: 'transparent',
    color: 'var(--color-text-secondary)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 500,
    textAlign: 'left',
    marginTop: 4,
    transition: 'background-color 0.15s ease, color 0.15s ease',
    boxSizing: 'border-box',
    flexShrink: 0,
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
      color: 'var(--color-accent)',
    },
  },
  /**
   * Mobile bottom drawer, rendered as a native modal `<dialog>` opened with
   * `showModal()`. The UA dialog styles (centering inset, `max-width`,
   * `max-height`, padding, border) are reset so the panel stays bottom-anchored
   * and full-bleed on mobile; `::backdrop` replaces the former hand-rolled
   * backdrop overlay and lives in the top layer instead of needing its own
   * `z-index`.
   */
  bottomDrawer: {
    position: 'fixed',
    top: 'auto',
    bottom: 0,
    left: 0,
    right: 0,
    margin: 0,
    marginLeft: 'auto',
    marginRight: 'auto',
    width: '100%',
    maxWidth: 540,
    maxHeight: 'min(520px, 80vh)',
    padding: 0,
    paddingBottom: 'calc(14px + env(safe-area-inset-bottom, 0px))',
    // Same border box as before it became a <dialog>: 1px on the top, left and
    // right edges, none on the bottom. The UA `dialog { border: solid }` is
    // neutralised first so only these edges are drawn.
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderBottomWidth: 0,
    borderBottomStyle: 'none',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: 'var(--color-background-surface)',
    color: 'inherit',
    boxShadow: '0 -8px 36px rgba(0, 0, 0, 0.28)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    boxSizing: 'border-box',
    animationName: slideUp,
    animationDuration: '0.24s',
    animationTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
    '@media (min-width: 769px)': {
      display: 'none',
    },
    '::backdrop': {
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      backdropFilter: 'blur(4px)',
      WebkitBackdropFilter: 'blur(4px)',
      animationName: fadeIn,
      animationDuration: '0.2s',
      animationTimingFunction: 'ease-out',
    },
  },
  drawerHandleArea: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 4,
    cursor: 'grab',
    touchAction: 'none',
    flexShrink: 0,
  },
  drawerHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'var(--color-border)',
  },
  drawerHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 6,
    paddingBottom: 12,
    paddingLeft: 20,
    paddingRight: 16,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    flexShrink: 0,
  },
  drawerTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: 'var(--color-text-primary)',
    margin: 0,
    letterSpacing: '-0.01em',
  },
  drawerCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 10,
    borderWidth: 0,
    borderStyle: 'none',
    backgroundColor: 'transparent',
    color: 'var(--color-text-secondary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease, color 0.15s ease',
    outline: 'none',
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
      color: 'var(--color-text-primary)',
    },
  },
  drawerBody: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 12,
    paddingRight: 12,
    scrollbarWidth: 'thin',
    scrollbarColor: 'var(--color-border) transparent',
  },
  drawerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    minHeight: 48,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 14,
    borderWidth: 0,
    borderStyle: 'none',
    backgroundColor: 'transparent',
    color: 'var(--color-text-secondary)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: 14.5,
    fontWeight: 500,
    textAlign: 'left',
    transition: 'background-color 0.15s ease, color 0.15s ease',
    boxSizing: 'border-box',
    marginBottom: 2,
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
      color: 'var(--color-text-primary)',
    },
    ':active': {
      backgroundColor: 'var(--color-background-muted)',
    },
  },
  drawerRowActive: {
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
    fontWeight: 600,
    ':hover': {
      backgroundColor: 'var(--color-accent-muted)',
      color: 'var(--color-accent)',
    },
  },
  drawerRowIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'var(--color-background-muted)',
    flexShrink: 0,
  },
  drawerRowIconWrapperActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  drawerRowLabel: {
    flex: 1,
    minWidth: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  drawerEmpty: {
    fontSize: 13.5,
    lineHeight: 1.5,
    color: 'var(--color-text-secondary)',
    paddingTop: 24,
    paddingBottom: 24,
    paddingLeft: 16,
    paddingRight: 16,
    textAlign: 'center',
  },
  drawerNewCollectionButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    width: 'calc(100% - 24px)',
    margin: '6px 12px 0 12px',
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 16,
    paddingRight: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'var(--color-border)',
    backgroundColor: 'transparent',
    color: 'var(--color-text-secondary)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: 14,
    fontWeight: 500,
    transition: 'background-color 0.15s ease, border-color 0.15s ease, color 0.15s ease',
    boxSizing: 'border-box',
    flexShrink: 0,
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
      borderColor: 'var(--color-accent)',
      color: 'var(--color-accent)',
    },
  },
});
