import * as stylex from '@stylexjs/stylex';

const nonDesktop = '@media (max-width: 1023px)';

export const styles = stylex.create({
  desktopNav: {
    position: 'fixed',
    top: 52,
    left: 0,
    bottom: 0,
    width: 240,
    backgroundColor: 'var(--color-background-surface)',
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: 'var(--color-border)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingTop: 20,
    paddingBottom: 24,
    paddingLeft: 16,
    paddingRight: 16,
    boxSizing: 'border-box',
    zIndex: 100,
    [nonDesktop]: {
      display: 'none',
    },
  },
  linksWrapper: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    flex: 1,
    minHeight: 0,
    // Clips the scroll pane below; the collections list owns its own scrolling.
    overflow: 'hidden',
  },
  activePill: {
    position: 'absolute',
    left: 0,
    width: 3,
    backgroundColor: 'var(--color-accent)',
    borderRadius: '0 2px 2px 0',
    opacity: 0,
    pointerEvents: 'none',
    zIndex: 2,
  },
  navSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    width: '100%',
    // Keep the primary links pinned while the collections pane below scrolls.
    flexShrink: 0,
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 12,
    borderWidth: 0,
    borderStyle: 'none',
    backgroundColor: 'transparent',
    color: 'var(--color-text-secondary)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: 13.5,
    fontWeight: 500,
    textAlign: 'left',
    transition: 'all 0.15s ease',
    textDecoration: 'none',
    width: '100%',
    boxSizing: 'border-box',
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
      color: 'var(--color-text-primary)',
    },
  },
  navItemActive: {
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
    fontWeight: 600,
    ':hover': {
      backgroundColor: 'var(--color-accent-muted)',
      color: 'var(--color-accent)',
    },
  },
  navLabel: {
    flex: 1,
    minWidth: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  countBadge: {
    flexShrink: 0,
    fontSize: 10,
    fontWeight: 600,
    lineHeight: 1.4,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 6,
    paddingRight: 6,
    borderRadius: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    color: 'var(--color-text-secondary)',
  },
  divider: {
    height: 1,
    backgroundColor: 'var(--color-border)',
    marginTop: 8,
    marginBottom: 8,
    marginLeft: 4,
    marginRight: 4,
    flexShrink: 0,
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingLeft: 12,
    paddingRight: 4,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--color-text-secondary)',
  },
  /**
   * Independent collections scroll pane: the list grows
   * inside a `flex: 1` pane that scrolls while the primary links above and the
   * trapezoid footer below stay pinned — no more pushing the footer off-screen.
   */
  collectionsScroll: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    boxSizing: 'border-box',
    // Slim scrollbar so the pane stays visually quiet inside the 240px rail.
    scrollbarWidth: 'thin',
    scrollbarColor: 'var(--color-border) transparent',
  },
  collectionIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: 0,
  },
  footerWrapper: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    marginTop: 'auto',
    marginLeft: -16,
    marginRight: -16,
    marginBottom: -24,
    boxSizing: 'border-box',
    zIndex: 150,
  },
  trapezoidButton: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 240,
    height: 58,
    borderWidth: 0,
    borderStyle: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    fontFamily: 'inherit',
    color: 'var(--color-text-secondary)',
    transition: 'color 0.15s ease',
    boxSizing: 'border-box',
    outline: 'none',
  },
  trapezoidButtonHover: {
    color: 'var(--color-accent)',
  },
  focusModeButton: {
    color: 'var(--color-text-secondary)',
    pointerEvents: 'auto',
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
      color: 'var(--color-text-primary)',
    },
  },
  trapezoidSvgBackdrop: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 240,
    height: 58,
    pointerEvents: 'none',
    overflow: 'visible',
  },
  backdropPath: {
    fill: 'var(--color-background-muted)',
    stroke: 'var(--color-border)',
    strokeWidth: 1,
    transition: 'fill 0.18s ease, stroke 0.18s ease',
  },
  backdropPathHover: {
    fill: 'var(--color-accent-muted)',
    stroke: 'var(--color-accent)',
  },
  buttonContent: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 240,
    height: 58,
    paddingTop: 14,
    paddingBottom: 6,
    paddingLeft: 24,
    paddingRight: 24,
    boxSizing: 'border-box',
  },
  labelGroup: {
    display: 'flex',
    alignItems: 'center',
    marginLeft: 8,
    marginRight: 'auto',
  },
  focusLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: 'inherit',
    whiteSpace: 'nowrap',
    letterSpacing: '-0.01em',
  },
  shortcutRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  kbd: {
    fontSize: 10,
    fontWeight: 600,
    color: 'var(--color-text-disabled)',
    backgroundColor: 'var(--color-background-surface)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'var(--color-border)',
    borderRadius: 4,
    paddingTop: 1.5,
    paddingBottom: 1.5,
    paddingLeft: 5,
    paddingRight: 5,
    fontFamily: 'inherit',
  },
  focusIcon: {
    color: 'inherit',
    flexShrink: 0,
  },
  iconCentered: {
    position: 'static',
    transform: 'none',
    margin: 'auto',
  },
});
