import * as stylex from '@stylexjs/stylex';

export const tablet = '@media (min-width: 769px) and (max-width: 1023px)';
export const mobile = '@media (max-width: 768px)';

export const sidebarStyles = stylex.create({
  wrapper: {
    position: 'relative',
  },
  navContainer: {
    position: 'fixed',
    top: 0,
    left: 0,
    bottom: 0,
    width: 240,
    backgroundColor: 'var(--color-background-surface)',
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: 'var(--color-border)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingTop: 24,
    paddingBottom: 24,
    paddingLeft: 16,
    paddingRight: 16,
    boxSizing: 'border-box',
    zIndex: 100,
    [tablet]: {
      top: 16,
      left: 16,
      bottom: 16,
      width: 60,
      borderRadius: 24,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'var(--color-border)',
      boxShadow: '0 12px 32px -4px rgba(0, 0, 0, 0.08)',
      paddingTop: 16,
      paddingBottom: 16,
      paddingLeft: 0,
      paddingRight: 0,
      alignItems: 'center',
      gap: 8,
    },
    [mobile]: {
      top: 'auto',
      bottom: 'calc(12px + env(safe-area-inset-bottom, 0px))',
      left: 16,
      right: 16,
      width: 'calc(100% - 32px)',
      height: 60,
      borderRadius: 20,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'var(--color-border)',
      boxShadow: '0 12px 32px -4px rgba(0, 0, 0, 0.08)',
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      alignItems: 'center',
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 12,
      paddingRight: 12,
    },
  },
  navSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    flex: 1,
    justifyContent: 'flex-start',
    [mobile]: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 'none',
    },
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    color: 'var(--color-text-disabled)',
    paddingLeft: 8,
    marginBottom: 6,
    [tablet]: {
      display: 'none',
    },
    [mobile]: {
      display: 'none',
    },
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 12,
    width: '100%',
    backgroundColor: 'transparent',
    borderStyle: 'none',
    borderWidth: 0,
    color: 'var(--color-text-secondary)',
    cursor: 'pointer',
    outline: 'none',
    fontFamily: 'inherit',
    fontSize: 14,
    fontWeight: 500,
    textAlign: 'left',
    transition: 'all 0.15s ease',
    boxSizing: 'border-box',
    ':hover': {
      backgroundColor: 'var(--color-background-muted)',
      color: 'var(--color-text-primary)',
    },
    [tablet]: {
      justifyContent: 'center',
      width: 44,
      height: 44,
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      borderRadius: 16,
    },
    [mobile]: {
      justifyContent: 'center',
      width: 44,
      height: 44,
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      borderRadius: 16,
    },
  },
  navItemActive: {
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
    fontWeight: 600,
  },
  // Amber treatment for material-active state — alpha-tint background + amber-600.
  navItemMaterialActive: {
    backgroundColor: 'rgba(217, 119, 6, 0.12)',
    color: '#d97706',
    fontWeight: 600,
  },
  navLabel: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: 1,
    [tablet]: {
      display: 'none',
    },
    [mobile]: {
      display: 'none',
    },
  },
  divider: {
    height: 1,
    backgroundColor: 'var(--color-border)',
    marginTop: 8,
    marginBottom: 8,
    opacity: 0.6,
    [tablet]: {
      width: 44,
      height: 1,
      margin: '4px 0',
    },
    [mobile]: {
      width: 1,
      height: 24,
      margin: '0 4px',
    },
  },
  activePill: {
    position: 'absolute',
    zIndex: 0,
    pointerEvents: 'none',
    opacity: 0,
    backgroundColor: 'var(--color-accent-muted)',
    borderRadius: 12,
  },
  mobileFocusButton: {
    display: 'none',
    [mobile]: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: 44,
      height: 44,
      flexShrink: 0,
      backgroundColor: 'transparent',
      borderStyle: 'none',
      borderRadius: 16,
      color: 'var(--color-text-secondary)',
      cursor: 'pointer',
      outline: 'none',
      transition: 'all 0.15s ease',
      ':hover': {
        backgroundColor: 'var(--color-background-muted)',
        color: 'var(--color-text-primary)',
      },
    },
  },
});
