import * as stylex from '@stylexjs/stylex';

// Borders carrying a `var()` role token are written as longhand triplets:
// StyleX silently drops a `border*` shorthand whose value contains `var()`
// (see `src/app/screens/AGENTS.md` / `materialCard.stylex.ts` convention).
// Radii come from the theme's own scale (`--radius-full` for circles/pills,
// `--radius-element` for surfaces) — `--radius-sm|md|lg` do not exist, and an
// undefined radius token drops to the initial value (square corners).
const reducedMotion = '@media (prefers-reduced-motion: reduce)';
const mobile = '@media (max-width: 768px)';

// StyleX-owned spin: the retired `className="animate-spin"` was a Tailwind
// leftover with no definition anywhere in the project, so spinners never
// actually animated (same pattern as `SyncStatusPill`'s `spin`).
const spin = stylex.keyframes({
  '0%': { transform: 'rotate(0deg)' },
  '100%': { transform: 'rotate(360deg)' },
});

export const importerStyles = stylex.create({
  content: {
    flex: 1,
    padding: '24px',
    overflowY: 'auto',
  },
  dropZoneWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    width: '100%',
  },
  dropZone: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: {
      default: 'var(--color-border-emphasized)',
      ':hover': 'var(--color-accent)',
    },
    borderRadius: '12px',
    padding: '48px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    backgroundColor: {
      default: 'var(--color-background-muted)',
      ':hover': 'var(--color-background-surface)',
    },
    textAlign: 'center',
    outline: {
      default: 'none',
      ':focus-visible': '2px solid var(--color-accent)',
    },
    outlineOffset: {
      default: '0px',
      ':focus-visible': '2px',
    },
    transitionProperty: 'border-color, background-color',
    transitionDuration: '0.2s',
    transitionTimingFunction: 'ease',
    [reducedMotion]: {
      transitionProperty: 'none',
    },
  },
  dropZoneActive: {
    borderColor: 'var(--color-accent)',
    backgroundColor: 'var(--color-accent-muted)',
  },
  dropZoneText: {
    marginTop: '16px',
    fontSize: '16px',
    color: 'var(--color-text-primary)',
    fontWeight: 500,
  },
  dropZoneHint: {
    marginTop: '8px',
    fontSize: '14px',
    color: 'var(--color-text-secondary)',
  },
  engineCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    padding: '16px 20px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-background-surface)',
    width: '100%',
    boxSizing: 'border-box',
  },
  engineInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  engineLabel: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
  },
  engineHint: {
    fontSize: 13,
    color: 'var(--color-text-secondary)',
    lineHeight: 1.4,
  },
  engineControlWrapper: {
    width: '100%',
  },
  fileList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '24px',
  },
  fileCard: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 18px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-background-surface)',
    gap: '16px',
    [mobile]: {
      flexDirection: 'column',
      alignItems: 'stretch',
      gap: '12px',
      padding: '14px 16px',
    },
  },
  fileMain: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flex: 1,
    minWidth: 0,
    [mobile]: {
      alignItems: 'flex-start',
      gap: '12px',
      width: '100%',
    },
  },
  fileInfo: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  fileName: {
    fontSize: 14,
    fontWeight: 500,
    color: 'var(--color-text-primary)',
    lineHeight: 1.4,
    overflowWrap: 'break-word',
    wordBreak: 'break-word',
  },
  fileMeta: {
    fontSize: '12px',
    color: 'var(--color-text-secondary)',
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  fileBadge: {
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
  },
  fileActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
    [mobile]: {
      width: '100%',
      justifyContent: 'flex-end',
      flexWrap: 'wrap',
      borderTopWidth: 1,
      borderTopStyle: 'solid',
      borderTopColor: 'var(--color-border)',
      paddingTop: '10px',
    },
  },
  // ── Status badge (`badgedot`) — the canonical LunaClair status pill ─────
  // Subtle muted fill, compact type, and a small dot (or spinner) that repeats
  // the text hue. The label is always rendered, so state never rests on colour
  // alone. Hues are the sentiment roles only (`--color-{success,warning,error}`)
  // plus accent for in-flight work; `--color-danger` does not exist in Astryx.
  badgedot: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    padding: '2px 8px',
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'capitalize',
    borderRadius: 'var(--radius-full)',
    whiteSpace: 'nowrap',
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 'var(--radius-full)',
    flexShrink: 0,
  },
  iconSpin: {
    animationName: spin,
    animationDuration: '1s',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'linear',
    [reducedMotion]: {
      animationName: 'none',
    },
  },
  badgePending: {
    backgroundColor: 'var(--color-background-muted)',
    color: 'var(--color-text-secondary)',
  },
  dotPending: { backgroundColor: 'var(--color-border-emphasized)' },
  badgeExtracting: {
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
  },
  badgeReview: {
    backgroundColor: 'var(--color-warning-muted)',
    color: 'var(--color-warning)',
  },
  dotReview: { backgroundColor: 'var(--color-warning)' },
  badgeDone: {
    backgroundColor: 'var(--color-success-muted)',
    color: 'var(--color-success)',
  },
  dotDone: { backgroundColor: 'var(--color-success)' },
  badgeError: {
    backgroundColor: 'var(--color-error-muted)',
    color: 'var(--color-error)',
  },
  dotError: { backgroundColor: 'var(--color-error)' },
  progressContainer: {
    marginTop: 8,
    width: '100%',
    height: 6,
    backgroundColor: 'var(--color-border)',
    borderRadius: 'var(--radius-full)',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: 'var(--color-accent)',
    borderRadius: 'var(--radius-full)',
    transitionProperty: 'width',
    transitionDuration: '0.3s',
    transitionTimingFunction: 'ease',
    [reducedMotion]: {
      transitionProperty: 'none',
    },
  },
  // ── Extraction progress card and header ─────────────────────────────────
  extractionViewHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '16px',
    marginBottom: 20,
  },
  extractionFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
  },
  extractionHeaderInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  extractionTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
    lineHeight: 1.3,
  },
  extractionSubtitle: {
    margin: 0,
    fontSize: 13,
    color: 'var(--color-text-secondary)',
    lineHeight: 1.4,
  },
  extractionCounterBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '2px 8px',
    fontSize: 11,
    fontWeight: 500,
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--color-background-muted)',
    color: 'var(--color-text-secondary)',
    width: 'fit-content',
    marginTop: 4,
  },
  extractionCard: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: '16px 20px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-background-surface)',
    gap: '16px',
    transitionProperty: 'border-color, box-shadow',
    transitionDuration: '0.2s',
    transitionTimingFunction: 'ease',
    [reducedMotion]: {
      transitionProperty: 'none',
    },
  },
  extractionCardActive: {
    borderColor: 'var(--color-accent)',
    boxShadow: '0 0 0 1px var(--color-accent)',
  },
  fileIconTile: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-background-muted)',
    color: 'var(--color-text-secondary)',
    flexShrink: 0,
    marginTop: 2,
  },
  fileIconTileActive: {
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
  },
  extractionCardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: '12px',
  },
  extractionProgressMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: 12,
    marginTop: 8,
    marginBottom: 4,
  },
  progressPercent: {
    fontWeight: 600,
    fontVariantNumeric: 'tabular-nums',
    color: 'var(--color-text-secondary)',
  },
  phaseIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: 12,
    color: 'var(--color-text-secondary)',
  },
  phaseIndicatorCooldown: {
    color: 'var(--color-warning)',
    fontWeight: 500,
  },
  phaseIndicatorVision: {
    color: 'var(--color-accent)',
    fontWeight: 500,
  },
  phaseIndicatorExtracting: {
    color: 'var(--color-text-primary)',
    fontWeight: 500,
  },
  fileErrorText: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: 12,
    color: 'var(--color-error)',
    marginTop: 4,
  },
  // ── Pinned wizard action bar ────────────────────────────────────────────
  actionBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '16px 0 0',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    backgroundColor: 'var(--color-background-surface)',
  },
  actionBarEnd: { justifyContent: 'flex-end' },
  actionBarSplit: { justifyContent: 'space-between' },
  // ── Review step ─────────────────────────────────────────────────────────
  // One review-level shell: a shared toolbar that is rendered in every view
  // mode (so the mode switcher can never unmount itself), then the body row of
  // sidebar + panes.
  reviewShell: {
    height: '100%',
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  reviewToolbar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    padding: '10px 14px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-background-surface)',
    [mobile]: {
      padding: '12px',
      gap: '10px',
    },
  },
  reviewToolbarRow1: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: '12px',
    minWidth: 0,
    [mobile]: {
      flexDirection: 'column',
      alignItems: 'stretch',
      gap: '10px',
    },
  },
  reviewToolbarRow2: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: '12px',
    paddingTop: '10px',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    [mobile]: {
      flexDirection: 'column',
      alignItems: 'stretch',
      gap: '8px',
    },
  },
  reviewToolbarRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
    [mobile]: {
      width: '100%',
      justifyContent: 'space-between',
      gap: '8px',
    },
  },
  reviewAiPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    paddingTop: '12px',
    marginTop: '2px',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    width: '100%',
  },
  reviewAiPanelHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
  },
  reviewAiPanelTitleGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  reviewAiPanelTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: 600,
    color: 'var(--color-text-primary)',
  },
  reviewAiPanelHint: {
    fontSize: '12px',
    color: 'var(--color-text-secondary)',
    lineHeight: 1.4,
  },
  reviewAiPanelActionsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    width: '100%',
    [mobile]: {
      flexDirection: 'column',
      alignItems: 'stretch',
      gap: '10px',
    },
  },
  reviewToolbarInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    minWidth: 0,
    // Anchors the file-selector popover to the toolbar's info block.
    position: 'relative',
    [mobile]: {
      width: '100%',
      justifyContent: 'space-between',
    },
  },
  reviewModeControlWrapper: {
    display: 'flex',
    flexShrink: 0,
    [mobile]: {
      flex: 1,
    },
  },
  reviewToolbarStaticFile: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    minWidth: 0,
  },
  reviewToolbarMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexShrink: 0,
  },
  fileSelectorTrigger: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    minWidth: 0,
    padding: '4px 8px',
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: 'var(--radius-element)',
    backgroundColor: {
      default: 'transparent',
      ':hover': 'var(--color-background-muted)',
    },
    color: 'var(--color-text-primary)',
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
  },
  fileIndex: {
    flexShrink: 0,
    fontSize: 12,
    fontWeight: 400,
    color: 'var(--color-text-secondary)',
  },
  fileKindIcon: {
    display: 'inline-flex',
    flexShrink: 0,
    color: 'var(--color-text-secondary)',
  },
  // Elevation uses a literal translucent shadow on purpose: the theme's shadow
  // scale is tuned for cards, and the app's other floating surfaces (ActionMenu,
  // the compact-collections popover) define their own shadows the same way.
  popover: {
    position: 'absolute',
    top: 'calc(100% + 4px)',
    left: 0,
    minWidth: 280,
    maxWidth: 'min(420px, calc(100vw - 32px))',
    maxHeight: 320,
    overflowY: 'auto',
    padding: 4,
    backgroundColor: 'var(--color-background-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--radius-element)',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.12)',
    zIndex: 50,
  },
  popoverItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    width: '100%',
    padding: '8px 12px',
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: 'var(--radius-element)',
    backgroundColor: {
      default: 'transparent',
      ':hover': 'var(--color-background-muted)',
    },
    color: 'var(--color-text-primary)',
    fontFamily: 'inherit',
    fontSize: 13,
    textAlign: 'left',
    cursor: 'pointer',
  },
  popoverItemSelected: {
    backgroundColor: 'var(--color-accent-muted)',
  },
  popoverFilename: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  reviewToolbarFilename: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--color-text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  reviewToolbarActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
    [mobile]: {
      width: '100%',
      flexDirection: 'column',
      alignItems: 'stretch',
      gap: '8px',
    },
  },
  reviewBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'row',
    gap: '16px',
    [mobile]: {
      flexDirection: 'column',
      overflowY: 'auto',
    },
  },
  pageTag: {
    padding: '1px 6px',
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--color-background-muted)',
    fontSize: 10,
    fontWeight: 600,
    color: 'var(--color-text-secondary)',
    whiteSpace: 'nowrap',
  },
  reviewCenter: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: '8px',
    overflow: 'hidden',
    [mobile]: {
      minHeight: '400px',
      flex: 'none',
    },
  },
  reviewRight: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: '8px',
    padding: '16px',
    overflowY: 'auto',
    [mobile]: {
      minHeight: '300px',
      flex: 'none',
    },
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 16px',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    backgroundColor: 'var(--color-background-muted)',
  },
  // ── Review banners ──────────────────────────────────────────────────────
  // Status strips above the panes (AI failure + retry, selection-cleanup
  // confirmation). The hue carries the meaning; the text always states it, so
  // nothing rests on colour alone — the same rule the status badge follows.
  bannerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '8px 16px',
    fontSize: 13,
  },
  bannerText: {
    flex: 1,
    minWidth: 0,
  },
  bannerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
  },
  bannerError: {
    backgroundColor: 'var(--color-error-muted)',
    color: 'var(--color-error)',
  },
  bannerSuccess: {
    backgroundColor: 'var(--color-success-muted)',
    color: 'var(--color-success)',
  },
  // ── Details step ────────────────────────────────────────────────────────
  detailsHeading: {
    margin: '0 0 16px',
    fontSize: 16,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
  },
  detailsSubtitle: {
    margin: '-10px 0 16px',
    fontSize: 13,
    color: 'var(--color-text-secondary)',
  },
  detailsCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    padding: '16px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-background-surface)',
    marginBottom: '16px',
  },
  detailsCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  detailsCardIcon: {
    width: 36,
    height: 36,
    flexShrink: 0,
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailsCardInfo: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  detailsCardFilename: {
    fontSize: 14,
    fontWeight: 500,
    color: 'var(--color-text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  detailsCardMeta: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8px',
    fontSize: 12,
    color: 'var(--color-text-secondary)',
  },
  detailsDivider: {
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
  },
  detailsHint: {
    fontSize: 12,
    color: 'var(--color-text-secondary)',
    lineHeight: 1.4,
    marginTop: -4,
  },
  // ── Results view (R1 — study handoff surface) ───────────────────────────
  // The saturated success container is gone: the handoff reads as a neutral
  // surface, and `--color-success(-muted)` is reserved for the celebration
  // badge and the per-material status, where it means "this object succeeded".
  resultContainer: {
    maxWidth: 520,
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '24px',
    padding: '16px 0',
  },
  successHeader: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '12px',
    textAlign: 'center',
  },
  successBadge: {
    width: 56,
    height: 56,
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--color-success-muted)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
    margin: 0,
  },
  resultSubtitle: {
    fontSize: 14,
    color: 'var(--color-text-secondary)',
    margin: 0,
  },
  resultMaterialList: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  resultMaterialRow: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    backgroundColor: 'var(--color-background-surface)',
    borderRadius: 'var(--radius-element)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
  },
  resultMaterialIcon: {
    width: 36,
    height: 36,
    flexShrink: 0,
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--color-accent-muted)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultMaterialInfo: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  resultMaterialTitle: {
    fontSize: 14,
    fontWeight: 500,
    color: 'var(--color-text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  resultMaterialMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: 12,
    color: 'var(--color-text-secondary)',
  },
  resultActionDeck: {
    display: 'flex',
    gap: '12px',
    marginTop: '8px',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  // ── Git-Style AI Cleanup Diff View ─────────────────────────────────────────
  diffShell: {
    height: '100%',
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  diffReviewBar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    padding: '10px 14px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-background-surface)',
    [mobile]: {
      padding: '12px',
      gap: '10px',
    },
  },
  diffReviewRow1: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: '12px',
    flexWrap: 'wrap',
    minWidth: 0,
    [mobile]: {
      flexDirection: 'column',
      alignItems: 'stretch',
      gap: '10px',
    },
  },
  diffReviewTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    minWidth: 0,
    [mobile]: {
      width: '100%',
      justifyContent: 'space-between',
    },
  },
  diffReviewRow2: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    width: '100%',
    paddingTop: '10px',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    [mobile]: {
      paddingTop: '8px',
    },
  },
  diffReviewHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
    minWidth: 0,
    [mobile]: {
      width: '100%',
      justifyContent: 'space-between',
    },
  },
  diffReviewTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  diffStats: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  diffStatAdd: {
    padding: '1px 6px',
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--color-success-muted)',
    color: 'var(--color-success)',
    fontSize: 11,
    fontWeight: 600,
    fontFamily: 'monospace',
  },
  diffStatDelete: {
    padding: '1px 6px',
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--color-error-muted)',
    color: 'var(--color-error)',
    fontSize: 11,
    fontWeight: 600,
    fontFamily: 'monospace',
  },
  diffActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    justifyContent: 'flex-end',
    flexShrink: 0,
    [mobile]: {
      width: '100%',
      flexDirection: 'column',
      alignItems: 'stretch',
      gap: '8px',
    },
  },
  diffViewContainer: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  diffSplitColumns: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'row',
    gap: '16px',
    [mobile]: {
      flexDirection: 'column',
      overflowY: 'auto',
    },
  },
  diffPane: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: '8px',
    overflow: 'hidden',
    backgroundColor: 'var(--color-background-surface)',
    [mobile]: {
      minHeight: '350px',
      flex: 'none',
    },
  },
  diffPaneHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 14px',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    backgroundColor: 'var(--color-background-muted)',
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
  },
  diffCodeBody: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    overflowX: 'auto',
    padding: '4px 0',
    backgroundColor: 'var(--color-background-surface)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 12,
  },
  diffLineRow: {
    display: 'flex',
    alignItems: 'flex-start',
    minHeight: '22px',
    lineHeight: '22px',
    paddingLeft: '4px',
    paddingRight: '8px',
  },
  diffLineRowEqual: {
    color: 'var(--color-text-primary)',
  },
  diffLineRowAdd: {
    backgroundColor: 'var(--color-success-muted)',
    color: 'var(--color-success)',
  },
  diffLineRowDelete: {
    backgroundColor: 'var(--color-error-muted)',
    color: 'var(--color-error)',
  },
  diffLineRowPlaceholder: {
    backgroundColor: 'var(--color-background-muted)',
  },
  diffLineGutter: {
    width: '36px',
    flexShrink: 0,
    userSelect: 'none',
    color: 'var(--color-text-secondary)',
    textAlign: 'right',
    paddingRight: '8px',
    fontSize: 11,
  },
  diffLineMarker: {
    width: '18px',
    flexShrink: 0,
    userSelect: 'none',
    textAlign: 'center',
    fontWeight: 700,
    fontSize: 12,
  },
  diffLineContent: {
    flex: 1,
    minWidth: 0,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
});
