import * as stylex from '@stylexjs/stylex';

// Borders carrying a `var()` role token are written as longhand triplets:
// StyleX silently drops a `border*` shorthand whose value contains `var()`
// (see `src/app/screens/AGENTS.md` / `materialCard.stylex.ts` convention).
// Radii come from the theme's own scale (`--radius-full` for circles/pills,
// `--radius-element` for surfaces) — `--radius-sm|md|lg` do not exist, and an
// undefined radius token drops to the initial value (square corners).
const reducedMotion = '@media (prefers-reduced-motion: reduce)';

// StyleX-owned spin: the retired `className="animate-spin"` was a Tailwind
// leftover with no definition anywhere in the project, so spinners never
// actually animated (same pattern as `SyncStatusPill`'s `spin`).
const spin = stylex.keyframes({
  '0%': { transform: 'rotate(0deg)' },
  '100%': { transform: 'rotate(360deg)' },
});

export const importerStyles = stylex.create({
  content: {
    flex: 1,
    padding: '24px',
    overflowY: 'auto',
  },
  dropZone: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: 'var(--color-border-emphasized)',
    borderRadius: '12px',
    padding: '48px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    backgroundColor: 'var(--color-background-muted)',
    textAlign: 'center',
  },
  dropZoneText: {
    marginTop: '16px',
    fontSize: '16px',
    color: 'var(--color-text-primary)',
    fontWeight: 500,
  },
  dropZoneHint: {
    marginTop: '8px',
    fontSize: '14px',
    color: 'var(--color-text-secondary)',
  },
  fileList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '24px',
  },
  fileCard: {
    display: 'flex',
    alignItems: 'center',
    padding: '16px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: '8px',
    backgroundColor: 'var(--color-background-surface)',
    gap: '16px',
  },
  fileInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  fileName: {
    fontWeight: 500,
    color: 'var(--color-text-primary)',
  },
  fileMeta: {
    fontSize: '12px',
    color: 'var(--color-text-secondary)',
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  // ── Status badge (`badgedot`) — the canonical LunaClair status pill ─────
  // Subtle muted fill, compact type, and a small dot (or spinner) that repeats
  // the text hue. The label is always rendered, so state never rests on colour
  // alone. Hues are the sentiment roles only (`--color-{success,warning,error}`)
  // plus accent for in-flight work; `--color-danger` does not exist in Astryx.
  badgedot: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    padding: '2px 8px',
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'capitalize',
    borderRadius: 'var(--radius-full)',
    whiteSpace: 'nowrap',
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 'var(--radius-full)',
    flexShrink: 0,
  },
  iconSpin: {
    animationName: spin,
    animationDuration: '1s',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'linear',
    [reducedMotion]: {
      animationName: 'none',
    },
  },
  badgePending: {
    backgroundColor: 'var(--color-background-muted)',
    color: 'var(--color-text-secondary)',
  },
  dotPending: { backgroundColor: 'var(--color-border-emphasized)' },
  badgeExtracting: {
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
  },
  badgeReview: {
    backgroundColor: 'var(--color-warning-muted)',
    color: 'var(--color-warning)',
  },
  dotReview: { backgroundColor: 'var(--color-warning)' },
  badgeDone: {
    backgroundColor: 'var(--color-success-muted)',
    color: 'var(--color-success)',
  },
  dotDone: { backgroundColor: 'var(--color-success)' },
  badgeError: {
    backgroundColor: 'var(--color-error-muted)',
    color: 'var(--color-error)',
  },
  dotError: { backgroundColor: 'var(--color-error)' },
  progressContainer: {
    marginTop: '8px',
    width: '100%',
    height: '4px',
    backgroundColor: 'var(--color-border)',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: 'var(--color-accent)',
    transition: 'width 0.3s ease',
  },
  // ── Pinned wizard action bar ────────────────────────────────────────────
  actionBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '16px 0 0',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    backgroundColor: 'var(--color-background-surface)',
  },
  actionBarEnd: { justifyContent: 'flex-end' },
  actionBarSplit: { justifyContent: 'space-between' },
  // ── Review step ─────────────────────────────────────────────────────────
  // One review-level shell: a shared toolbar that is rendered in every view
  // mode (so the mode switcher can never unmount itself), then the body row of
  // sidebar + panes.
  reviewShell: {
    height: '100%',
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  reviewToolbar: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '12px',
    padding: '8px 12px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-background-surface)',
  },
  reviewToolbarInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 180,
    minWidth: 0,
    // Anchors the file-selector popover to the toolbar's info block. Keeping it
    // here (rather than in a wrapper div) leaves this element the toolbar's
    // growing flex item, so the switcher and actions stay where they were.
    position: 'relative',
  },
  fileSelectorTrigger: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    minWidth: 0,
    padding: '4px 8px',
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: 'var(--radius-element)',
    backgroundColor: {
      default: 'transparent',
      ':hover': 'var(--color-background-muted)',
    },
    color: 'var(--color-text-primary)',
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
  },
  fileIndex: {
    flexShrink: 0,
    fontSize: 12,
    fontWeight: 400,
    color: 'var(--color-text-secondary)',
  },
  fileKindIcon: {
    display: 'inline-flex',
    flexShrink: 0,
    color: 'var(--color-text-secondary)',
  },
  // Elevation uses a literal translucent shadow on purpose: the theme's shadow
  // scale is tuned for cards, and the app's other floating surfaces (ActionMenu,
  // the compact-collections popover) define their own shadows the same way.
  popover: {
    position: 'absolute',
    top: 'calc(100% + 4px)',
    left: 0,
    minWidth: 280,
    maxWidth: 'min(420px, calc(100vw - 32px))',
    maxHeight: 320,
    overflowY: 'auto',
    padding: 4,
    backgroundColor: 'var(--color-background-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--radius-element)',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.12)',
    zIndex: 50,
  },
  popoverItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    width: '100%',
    padding: '8px 12px',
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: 'var(--radius-element)',
    backgroundColor: {
      default: 'transparent',
      ':hover': 'var(--color-background-muted)',
    },
    color: 'var(--color-text-primary)',
    fontFamily: 'inherit',
    fontSize: 13,
    textAlign: 'left',
    cursor: 'pointer',
  },
  popoverItemSelected: {
    backgroundColor: 'var(--color-accent-muted)',
  },
  popoverFilename: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  reviewToolbarFilename: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--color-text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  reviewToolbarActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
  },
  reviewBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    gap: '16px',
  },
  pageTag: {
    padding: '1px 6px',
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--color-background-muted)',
    fontSize: 10,
    fontWeight: 600,
    color: 'var(--color-text-secondary)',
    whiteSpace: 'nowrap',
  },
  reviewCenter: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  reviewRight: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: '8px',
    padding: '16px',
    overflowY: 'auto',
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 16px',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    backgroundColor: 'var(--color-background-muted)',
  },
  // ── Details step ────────────────────────────────────────────────────────
  detailsHeading: {
    margin: '0 0 16px',
    fontSize: 16,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
  },
  detailsCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    padding: '16px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-background-surface)',
    marginBottom: '16px',
  },
  detailsCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  detailsCardIcon: {
    width: 36,
    height: 36,
    flexShrink: 0,
    borderRadius: 'var(--radius-element)',
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailsCardInfo: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  detailsCardFilename: {
    fontSize: 14,
    fontWeight: 500,
    color: 'var(--color-text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  detailsCardMeta: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8px',
    fontSize: 12,
    color: 'var(--color-text-secondary)',
  },
  // ── Results view (R1 — study handoff surface) ───────────────────────────
  // The saturated success container is gone: the handoff reads as a neutral
  // surface, and `--color-success(-muted)` is reserved for the celebration
  // badge and the per-material status, where it means "this object succeeded".
  resultContainer: {
    maxWidth: 520,
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '24px',
    padding: '16px 0',
  },
  successHeader: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '12px',
    textAlign: 'center',
  },
  successBadge: {
    width: 56,
    height: 56,
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--color-success-muted)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: 'var(--color-text-primary)',
    margin: 0,
  },
  resultSubtitle: {
    fontSize: 14,
    color: 'var(--color-text-secondary)',
    margin: 0,
  },
  resultMaterialList: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  resultMaterialRow: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    backgroundColor: 'var(--color-background-surface)',
    borderRadius: 'var(--radius-element)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
  },
  resultMaterialIcon: {
    width: 36,
    height: 36,
    flexShrink: 0,
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--color-accent-muted)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultMaterialInfo: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  resultMaterialTitle: {
    fontSize: 14,
    fontWeight: 500,
    color: 'var(--color-text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  resultMaterialMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: 12,
    color: 'var(--color-text-secondary)',
  },
  resultActionDeck: {
    display: 'flex',
    gap: '12px',
    marginTop: '8px',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
});
