import * as stylex from '@stylexjs/stylex';

export const importerStyles = stylex.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    backgroundColor: '#ffffff',
  },
  header: {
    padding: '24px',
    borderBottom: '1px solid #e5e7eb',
  },
  wizardSteps: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    fontSize: '14px',
    color: 'var(--color-text-secondary)',
  },
  activeStep: {
    color: 'var(--color-accent)',
    fontWeight: 'bold',
  },
  content: {
    flex: 1,
    padding: '24px',
    overflowY: 'auto',
  },
  dropZone: {
    border: '2px dashed var(--color-border-emphasized)',
    borderRadius: '12px',
    padding: '48px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    backgroundColor: 'var(--color-background-muted)',
    textAlign: 'center',
  },
  dropZoneActive: {
    borderColor: 'var(--color-accent)',
    backgroundColor: 'var(--color-accent-muted)',
  },
  dropZoneText: {
    marginTop: '16px',
    fontSize: '16px',
    color: 'var(--color-text-primary)',
    fontWeight: 500,
  },
  dropZoneHint: {
    marginTop: '8px',
    fontSize: '14px',
    color: 'var(--color-text-secondary)',
  },
  formatBadges: {
    display: 'flex',
    gap: '8px',
    marginTop: '16px',
  },
  badge: {
    padding: '4px 8px',
    borderRadius: '16px',
    backgroundColor: 'var(--color-background-muted)',
    fontSize: '12px',
    color: 'var(--color-text-secondary)',
    fontWeight: 500,
  },
  fileList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '24px',
  },
  fileCard: {
    display: 'flex',
    alignItems: 'center',
    padding: '16px',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    gap: '16px',
  },
  fileInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  fileName: {
    fontWeight: 500,
    color: '#1f2937',
  },
  fileMeta: {
    fontSize: '12px',
    color: '#6b7280',
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  statusBadge: {
    padding: '4px 8px',
    borderRadius: '16px',
    fontSize: '12px',
    fontWeight: 500,
  },
  statusPending: { backgroundColor: 'var(--color-background-muted)', color: 'var(--color-text-secondary)' },
  statusExtracting: { backgroundColor: 'var(--color-accent-muted)', color: 'var(--color-accent)' },
  statusReview: { backgroundColor: '#fef3c7', color: '#d97706' },
  statusError: { backgroundColor: '#fee2e2', color: '#dc2626' },
  statusDone: { backgroundColor: 'var(--color-success-muted)', color: 'var(--color-success)' },
  progressContainer: {
    marginTop: '8px',
    width: '100%',
    height: '4px',
    backgroundColor: '#e5e7eb',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: 'var(--color-accent)',
    transition: 'width 0.3s ease',
  },
  reviewLayout: {
    display: 'flex',
    height: '100%',
    gap: '16px',
  },
  reviewLeft: {
    width: '250px',
    borderRight: '1px solid #e5e7eb',
    paddingRight: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    overflowY: 'auto',
  },
  reviewCenter: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  reviewRight: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: '16px',
    overflowY: 'auto',
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 16px',
    borderBottom: '1px solid #e5e7eb',
    backgroundColor: '#f9fafb',
  },
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '8px 16px',
    borderRadius: '6px',
    fontWeight: 500,
    cursor: 'pointer',
    border: 'none',
  },
  buttonPrimary: {
    backgroundColor: 'var(--color-accent)',
    color: '#ffffff',
  },
  buttonSecondary: {
    backgroundColor: 'var(--color-background-muted)',
    color: 'var(--color-text-primary)',
  },
  buttonDanger: {
    backgroundColor: 'var(--color-error)',
    color: '#ffffff',
  },
  buttonGhost: {
    backgroundColor: 'transparent',
    color: 'var(--color-text-secondary)',
  },
  diffModal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  diffCard: {
    width: '90%',
    maxWidth: '1200px',
    height: '90%',
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    display: 'flex',
    flexDirection: 'column',
  },
  diffHeader: {
    padding: '16px',
    borderBottom: '1px solid #e5e7eb',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  diffContent: {
    flex: 1,
    display: 'flex',
    gap: '16px',
    padding: '16px',
    overflow: 'hidden',
  },
  diffPane: {
    flex: 1,
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: '16px',
    overflowY: 'auto',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginBottom: '16px',
  },
  label: {
    fontWeight: 500,
    fontSize: '14px',
    color: '#1f2937',
  },
  input: {
    padding: '8px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    fontSize: '14px',
  },
  select: {
    padding: '8px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    fontSize: '14px',
    backgroundColor: '#ffffff',
  },
  resultCard: {
    padding: '24px',
    border: '1px solid var(--color-success)',
    borderRadius: '8px',
    backgroundColor: 'var(--color-success-muted)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
  },
});
