import type { EditorThemeClasses } from 'lexical';
import './writer.css';

export const writerTheme: EditorThemeClasses = {
  ltr: 'writer-ltr',
  rtl: 'writer-rtl',
  placeholder: 'writer-placeholder',
  paragraph: 'writer-paragraph',
  quote: 'writer-quote',
  heading: {
    h1: 'writer-h1',
    h2: 'writer-h2',
    h3: 'writer-h3',
    h4: 'writer-h4',
    h5: 'writer-h5',
    h6: 'writer-h6',
  },
  list: {
    nested: {
      listitem: 'writer-nested-listitem',
    },
    ol: 'writer-list-ol',
    ul: 'writer-list-ul',
    listitem: 'writer-listitem',
    listitemChecked: 'writer-listitem-checked',
    listitemUnchecked: 'writer-listitem-unchecked',
  },
  image: 'writer-image',
  link: 'writer-link',
  text: {
    bold: 'writer-text-bold',
    italic: 'writer-text-italic',
    underline: 'writer-text-underline',
    strikethrough: 'writer-text-strikethrough',
    underlineStrikethrough: 'writer-text-underline-strikethrough',
    code: 'writer-text-code',
    subscript: 'writer-text-subscript',
    superscript: 'writer-text-superscript',
    highlight: 'writer-text-highlight',
  },
  code: 'writer-code-block',
  codeHighlight: {
    atrule: 'writer-tokenAttr',
    attr: 'writer-tokenAttr',
    boolean: 'writer-tokenProperty',
    builtin: 'writer-tokenSelector',
    cdata: 'writer-tokenComment',
    char: 'writer-tokenSelector',
    class: 'writer-tokenFunction',
    'class-name': 'writer-tokenFunction',
    comment: 'writer-tokenComment',
    constant: 'writer-tokenProperty',
    deleted: 'writer-tokenProperty',
    doctype: 'writer-tokenComment',
    entity: 'writer-tokenOperator',
    function: 'writer-tokenFunction',
    important: 'writer-tokenVariable',
    inserted: 'writer-tokenSelector',
    keyword: 'writer-tokenAttr',
    namespace: 'writer-tokenVariable',
    number: 'writer-tokenProperty',
    operator: 'writer-tokenOperator',
    prolog: 'writer-tokenComment',
    property: 'writer-tokenProperty',
    punctuation: 'writer-tokenPunctuation',
    regex: 'writer-tokenVariable',
    selector: 'writer-tokenSelector',
    string: 'writer-tokenSelector',
    symbol: 'writer-tokenProperty',
    tag: 'writer-tokenProperty',
    url: 'writer-tokenOperator',
    variable: 'writer-tokenVariable',
  },
  table: 'writer-table',
  tableCell: 'writer-table-cell',
  tableCellHeader: 'writer-table-cell-header',
  tableRow: 'writer-table-row',
  hr: 'writer-hr',
};
